// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mavs/mavs/stored_voting.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StoredVoting struct {
	Index         string            `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Timewindow    string            `protobuf:"bytes,2,opt,name=timewindow,proto3" json:"timewindow,omitempty"`
	Counting      map[string]uint64 `protobuf:"bytes,3,rep,name=counting,proto3" json:"counting,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Title         string            `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	ElectoralRoll *ElectoralRoll    `protobuf:"bytes,5,opt,name=electoral_roll,json=electoralRoll,proto3" json:"electoral_roll,omitempty"`
	Creator       string            `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *StoredVoting) Reset()         { *m = StoredVoting{} }
func (m *StoredVoting) String() string { return proto.CompactTextString(m) }
func (*StoredVoting) ProtoMessage()    {}
func (*StoredVoting) Descriptor() ([]byte, []int) {
	return fileDescriptor_162f2f61ca5a0076, []int{0}
}
func (m *StoredVoting) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredVoting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredVoting.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredVoting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredVoting.Merge(m, src)
}
func (m *StoredVoting) XXX_Size() int {
	return m.Size()
}
func (m *StoredVoting) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredVoting.DiscardUnknown(m)
}

var xxx_messageInfo_StoredVoting proto.InternalMessageInfo

func (m *StoredVoting) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *StoredVoting) GetTimewindow() string {
	if m != nil {
		return m.Timewindow
	}
	return ""
}

func (m *StoredVoting) GetCounting() map[string]uint64 {
	if m != nil {
		return m.Counting
	}
	return nil
}

func (m *StoredVoting) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *StoredVoting) GetElectoralRoll() *ElectoralRoll {
	if m != nil {
		return m.ElectoralRoll
	}
	return nil
}

func (m *StoredVoting) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*StoredVoting)(nil), "mavs.mavs.StoredVoting")
	proto.RegisterMapType((map[string]uint64)(nil), "mavs.mavs.StoredVoting.CountingEntry")
}

func init() { proto.RegisterFile("mavs/mavs/stored_voting.proto", fileDescriptor_162f2f61ca5a0076) }

var fileDescriptor_162f2f61ca5a0076 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0xcd, 0x4e, 0x32, 0x31,
	0x14, 0xa5, 0xfc, 0x7d, 0x1f, 0x45, 0x8c, 0x69, 0x5c, 0x34, 0x24, 0x36, 0xc4, 0x44, 0xc3, 0x6a,
	0x26, 0xc1, 0x8d, 0xd1, 0x85, 0xa2, 0xe1, 0x05, 0x86, 0x84, 0x85, 0x1b, 0x32, 0x0c, 0x57, 0x6c,
	0xec, 0xcc, 0x25, 0xa5, 0xfc, 0xbd, 0x85, 0x2f, 0xe3, 0x3b, 0xb8, 0x64, 0xe9, 0xd2, 0x30, 0x2f,
	0x62, 0xda, 0x01, 0x1c, 0x36, 0x37, 0x3d, 0xbd, 0xe7, 0x9e, 0x73, 0x6e, 0x2e, 0xbd, 0x88, 0xc3,
	0xc5, 0xcc, 0x77, 0x65, 0x66, 0x50, 0xc3, 0x78, 0xb8, 0x40, 0x23, 0x93, 0x89, 0x37, 0xd5, 0x68,
	0x90, 0xd5, 0x6c, 0xc7, 0xb3, 0xa5, 0x29, 0xfe, 0x98, 0xa0, 0x20, 0x32, 0xa8, 0x43, 0x35, 0xd4,
	0xa8, 0x54, 0x46, 0xbd, 0xfc, 0x2c, 0xd2, 0x93, 0xbe, 0x93, 0x18, 0x38, 0x05, 0x76, 0x4e, 0x2b,
	0x32, 0x19, 0xc3, 0x8a, 0x93, 0x16, 0x69, 0xd7, 0x82, 0x0c, 0x30, 0x41, 0xa9, 0x91, 0x31, 0x2c,
	0x65, 0x32, 0xc6, 0x25, 0x2f, 0xba, 0x56, 0xee, 0x87, 0x75, 0xe9, 0xff, 0x08, 0xe7, 0x89, 0x55,
	0xe0, 0xa5, 0x56, 0xa9, 0x5d, 0xef, 0x5c, 0x79, 0x87, 0x10, 0x5e, 0xde, 0xc0, 0x7b, 0xde, 0xf1,
	0x7a, 0x89, 0xd1, 0xeb, 0xe0, 0x30, 0x66, 0x8d, 0x8d, 0x34, 0x0a, 0x78, 0x39, 0x33, 0x76, 0x80,
	0x3d, 0xd0, 0xd3, 0xe3, 0xdc, 0xbc, 0xd2, 0x22, 0xed, 0x7a, 0x87, 0xe7, 0xe4, 0x7b, 0x7b, 0x42,
	0x80, 0x4a, 0x05, 0x0d, 0xc8, 0x43, 0xc6, 0xe9, 0xbf, 0x48, 0x43, 0x68, 0x50, 0xf3, 0xaa, 0x13,
	0xde, 0xc3, 0xe6, 0x3d, 0x6d, 0x1c, 0x65, 0x61, 0x67, 0xb4, 0xf4, 0x0e, 0xeb, 0xdd, 0xe2, 0xf6,
	0x69, 0x33, 0x2d, 0x42, 0x35, 0x07, 0xb7, 0x71, 0x39, 0xc8, 0xc0, 0x5d, 0xf1, 0x96, 0x3c, 0x3d,
	0x7e, 0x6d, 0x05, 0xd9, 0x6c, 0x05, 0xf9, 0xd9, 0x0a, 0xf2, 0x91, 0x8a, 0xc2, 0x26, 0x15, 0x85,
	0xef, 0x54, 0x14, 0x5e, 0xae, 0x27, 0xd2, 0xbc, 0xcd, 0x47, 0x5e, 0x84, 0xb1, 0x0f, 0x71, 0xf8,
	0x8a, 0x5a, 0xc9, 0xc4, 0x8f, 0xbb, 0x83, 0xbe, 0xbf, 0xca, 0x0e, 0x61, 0xd6, 0x53, 0x98, 0x8d,
	0xaa, 0xee, 0x00, 0x37, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xf7, 0xe6, 0xc9, 0xcc, 0x01,
	0x00, 0x00,
}

func (m *StoredVoting) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredVoting) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredVoting) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintStoredVoting(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	if m.ElectoralRoll != nil {
		{
			size, err := m.ElectoralRoll.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredVoting(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintStoredVoting(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Counting) > 0 {
		for k := range m.Counting {
			v := m.Counting[k]
			baseI := i
			i = encodeVarintStoredVoting(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintStoredVoting(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintStoredVoting(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Timewindow) > 0 {
		i -= len(m.Timewindow)
		copy(dAtA[i:], m.Timewindow)
		i = encodeVarintStoredVoting(dAtA, i, uint64(len(m.Timewindow)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintStoredVoting(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStoredVoting(dAtA []byte, offset int, v uint64) int {
	offset -= sovStoredVoting(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StoredVoting) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovStoredVoting(uint64(l))
	}
	l = len(m.Timewindow)
	if l > 0 {
		n += 1 + l + sovStoredVoting(uint64(l))
	}
	if len(m.Counting) > 0 {
		for k, v := range m.Counting {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovStoredVoting(uint64(len(k))) + 1 + sovStoredVoting(uint64(v))
			n += mapEntrySize + 1 + sovStoredVoting(uint64(mapEntrySize))
		}
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovStoredVoting(uint64(l))
	}
	if m.ElectoralRoll != nil {
		l = m.ElectoralRoll.Size()
		n += 1 + l + sovStoredVoting(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovStoredVoting(uint64(l))
	}
	return n
}

func sovStoredVoting(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStoredVoting(x uint64) (n int) {
	return sovStoredVoting(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StoredVoting) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStoredVoting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredVoting: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredVoting: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredVoting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timewindow", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredVoting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timewindow = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counting", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredVoting
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Counting == nil {
				m.Counting = make(map[string]uint64)
			}
			var mapkey string
			var mapvalue uint64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowStoredVoting
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStoredVoting
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthStoredVoting
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthStoredVoting
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowStoredVoting
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipStoredVoting(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthStoredVoting
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Counting[mapkey] = mapvalue
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredVoting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ElectoralRoll", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredVoting
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ElectoralRoll == nil {
				m.ElectoralRoll = &ElectoralRoll{}
			}
			if err := m.ElectoralRoll.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredVoting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredVoting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredVoting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStoredVoting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStoredVoting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStoredVoting(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStoredVoting
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStoredVoting
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStoredVoting
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStoredVoting
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStoredVoting
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStoredVoting
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStoredVoting        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStoredVoting          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStoredVoting = fmt.Errorf("proto: unexpected end of group")
)
